### ISSUE TITLE
SHA256 doesn't match the file

### ISSUE THREAD

**Issue by stangier** [ros-melodic-arch/ros-melodic-tf2-geometry-msgs#1]
Hello,
when trying to install this package, the vailidty check fails. Also when downloading and generating the SHA256 file manually it doesn't match with the one SHA256 given in the PKGBUILD. The SHA256 I get is:
`f1516df538999a5fb7cb8eeaf71636c9572bba758adac8cdafbf5446918b7bbc`
This may be solved by just changing the checksum in the PKGBUILD but I'm not sure if there any deeper issues that cause that.

**Comment by bionade24** [comment]
You have to skip currently, since there is a more fundamental problem with checksums caused by ´ros-gbp`. I'll try to fix all packages as soon as I can, but you can also help us. More info is in our project.

**Comment by bionade24** [comment]
Solved in https://github.com/ros-melodic-arch/ros-melodic-tf2-geometry-msgs/pull/2
